name: cxf-spring-cloud-netflix-docker

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 12
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: 12

    - name: Build with Maven
      run: mvn -B test --no-transfer-progress --file pom.xml
